; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = FailDeadly
include_dir = Inc
src_dir = Src

[env:FailDeadly]
platform = ststm32
board = genericSTM32F401CC
framework = stm32cube
board_build.ldscript = linker/STM32F401CCUx_MPU.ld

extra_scripts =
    pre:scripts/build_mbedtls.py

upload_protocol = custom
debug_tool = stlink
upload_flags = 
	-s
	${platformio.packages_dir}/tool-openocd/scripts
	-f
	interface/stlink.cfg
	-c
	transport select swd; adapter speed 1000;
	-f
	target/stm32f4x.cfg
	-c
	init; reset halt
	-c
	program $SOURCE 0x08000000 verify reset
upload_command = ${platformio.packages_dir}/tool-openocd/bin/openocd $UPLOAD_FLAGS -c "shutdown"
build_type = debug
build_flags = 
	-mcpu=cortex-m4
	-mfpu=fpv4-sp-d16
	-mfloat-abi=softfp
	-DSTM32F401xC
	-DUSE_HAL_DRIVER
	-DARM_MATH_CM4
    -DUSE_FULL_ASSERT

    -Ilib/MbedTLS/mbedtls/tf-psa-crypto/include
    -Ilib/MbedTLS/mbedtls/tf-psa-crypto/drivers/builtin/include
    -Iconfig

    -DTF_PSA_CRYPTO_CONFIG_FILE=\"faildeadly_tf_psa_crypto_config.h\"

    -ffunction-sections
    -fdata-sections

build_unflags =
    -fexceptions
    -frtti
    -std=gnu++11
build_src_filter = 
	+<*>

monitor_speed = 115200
check_tool = cppcheck, clangtidy
lib_ldf_mode = deep
platform_packages = 
    platformio/framework-stm32cubef4@^1.28.1
lib_deps =
    MbedTLS
